/*******************************************************************************
 * Copyright (c) 2000, 2022 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
							TokenNameWHITESPACE = 1000,
							TokenNameCOMMENT_LINE = 1001,
							TokenNameCOMMENT_BLOCK = 1002,
							TokenNameCOMMENT_JAVADOC = 1003,
							TokenNameSingleQuoteStringLiteral = 1004,
							TokenNameCOMMENT_MARKDOWN = 1005;

	static boolean isRestrictedKeyword(int tokenType) {
		return switch (tokenType) {
			case TokenNameRestrictedIdentifierYield, TokenNameRestrictedIdentifierrecord,TokenNameRestrictedIdentifierWhen,
					TokenNameRestrictedIdentifiersealed, TokenNameRestrictedIdentifierpermits -> true;
			default -> false;
		};
	}

	static int getRestrictedKeyword(char [] text) {
		if (text != null) {
			int len = text.length;
			if (len == 4 && text[0] == 'w' ||
				len == 5 && text[0] == 'y' ||
				len == 6 && (text[0] == 'r' || text[0] == 's') ||
				len == 7 && text[0] == 'p') {
				return getRestrictedKeyword(new String(text));
			}
		}
		return TokenNameNotAToken;
	}

	static int getRestrictedKeyword(String text) {
		return switch (text) {
			case "yield"   -> TokenNameRestrictedIdentifierYield;   //$NON-NLS-1$
			case "record"  -> TokenNameRestrictedIdentifierrecord;  //$NON-NLS-1$
			case "when"    -> TokenNameRestrictedIdentifierWhen;    //$NON-NLS-1$
			case "sealed"  -> TokenNameRestrictedIdentifiersealed;  //$NON-NLS-1$
			case "permits" -> TokenNameRestrictedIdentifierpermits; //$NON-NLS-1$
			default        -> TokenNameNotAToken;
		};
	}

	// BEGIN_AUTOGENERATED_REGION
	int TokenNameIdentifier = 19,
							TokenNameabstract = 44,
							TokenNameassert = 85,
							TokenNameboolean = 108,
							TokenNamebreak = 86,
							TokenNamebyte = 109,
							TokenNamecase = 110,
							TokenNamecatch = 111,
							TokenNamechar = 112,
							TokenNameclass = 73,
							TokenNamecontinue = 87,
							TokenNameconst = 139,
							TokenNamedefault = 81,
							TokenNamedo = 88,
							TokenNamedouble = 113,
							TokenNameelse = 124,
							TokenNameenum = 78,
							TokenNameextends = 96,
							TokenNamefalse = 55,
							TokenNamefinal = 45,
							TokenNamefinally = 122,
							TokenNamefloat = 114,
							TokenNamefor = 89,
							TokenNamegoto = 140,
							TokenNameif = 90,
							TokenNameimplements = 136,
							TokenNameimport = 115,
							TokenNameinstanceof = 17,
							TokenNameint = 116,
							TokenNameinterface = 76,
							TokenNamelong = 117,
							TokenNamenative = 46,
							TokenNamenew = 38,
							TokenNamenon_sealed = 47,
							TokenNamenull = 56,
							TokenNamepackage = 95,
							TokenNameprivate = 48,
							TokenNameprotected = 49,
							TokenNamepublic = 50,
							TokenNamereturn = 91,
							TokenNameshort = 118,
							TokenNamestatic = 39,
							TokenNamestrictfp = 51,
							TokenNamesuper = 35,
							TokenNameswitch = 67,
							TokenNamesynchronized = 41,
							TokenNamethis = 36,
							TokenNamethrow = 83,
							TokenNamethrows = 123,
							TokenNametransient = 52,
							TokenNametrue = 57,
							TokenNametry = 92,
							TokenNamevoid = 119,
							TokenNamevolatile = 53,
							TokenNamewhile = 84,
							TokenNamemodule = 120,
							TokenNameopen = 125,
							TokenNamerequires = 126,
							TokenNametransitive = 131,
							TokenNameexports = 127,
							TokenNameopens = 128,
							TokenNameto = 137,
							TokenNameuses = 129,
							TokenNameprovides = 130,
							TokenNamewith = 138,
							TokenNameIntegerLiteral = 58,
							TokenNameLongLiteral = 59,
							TokenNameFloatingPointLiteral = 60,
							TokenNameDoubleLiteral = 61,
							TokenNameCharacterLiteral = 62,
							TokenNameStringLiteral = 63,
							TokenNameTextBlock = 64,
							TokenNamePLUS_PLUS = 2,
							TokenNameMINUS_MINUS = 3,
							TokenNameEQUAL_EQUAL = 20,
							TokenNameLESS_EQUAL = 12,
							TokenNameGREATER_EQUAL = 13,
							TokenNameNOT_EQUAL = 21,
							TokenNameLEFT_SHIFT = 18,
							TokenNameRIGHT_SHIFT = 14,
							TokenNameUNSIGNED_RIGHT_SHIFT = 16,
							TokenNamePLUS_EQUAL = 97,
							TokenNameMINUS_EQUAL = 98,
							TokenNameMULTIPLY_EQUAL = 99,
							TokenNameDIVIDE_EQUAL = 100,
							TokenNameAND_EQUAL = 101,
							TokenNameOR_EQUAL = 102,
							TokenNameXOR_EQUAL = 103,
							TokenNameREMAINDER_EQUAL = 104,
							TokenNameLEFT_SHIFT_EQUAL = 105,
							TokenNameRIGHT_SHIFT_EQUAL = 106,
							TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 107,
							TokenNameOR_OR = 31,
							TokenNameAND_AND = 30,
							TokenNamePLUS = 4,
							TokenNameMINUS = 5,
							TokenNameNOT = 68,
							TokenNameREMAINDER = 9,
							TokenNameXOR = 25,
							TokenNameAND = 22,
							TokenNameMULTIPLY = 8,
							TokenNameOR = 28,
							TokenNameTWIDDLE = 69,
							TokenNameDIVIDE = 10,
							TokenNameGREATER = 15,
							TokenNameLESS = 11,
							TokenNameLPAREN = 23,
							TokenNameRPAREN = 24,
							TokenNameLBRACE = 42,
							TokenNameRBRACE = 33,
							TokenNameLBRACKET = 6,
							TokenNameRBRACKET = 72,
							TokenNameSEMICOLON = 26,
							TokenNameQUESTION = 29,
							TokenNameCOLON = 70,
							TokenNameCOMMA = 32,
							TokenNameDOT = 1,
							TokenNameEQUAL = 82,
							TokenNameAT = 37,
							TokenNameELLIPSIS = 80,
							TokenNameARROW = 121,
							TokenNameCOLON_COLON = 7,
							TokenNameBeginLambda = 65,
							TokenNameBeginIntersectionCast = 71,
							TokenNameBeginTypeArguments = 93,
							TokenNameElidedSemicolonAndRightBrace = 141,
							TokenNameAT308 = 27,
							TokenNameAT308DOTDOTDOT = 132,
							TokenNameJAVADOC_FORMAL_PART_START = 54,
							TokenNameJAVADOC_FORMAL_PART_SEPARATOR = 74,
							TokenNameJAVADOC_FORMAL_PART_END = 75,
							TokenNameold = 66,
							TokenNameCaseArrow = 77,
							TokenNameRestrictedIdentifierYield = 94,
							TokenNameRestrictedIdentifierrecord = 79,
							TokenNameRestrictedIdentifiersealed = 43,
							TokenNameRestrictedIdentifierpermits = 133,
							TokenNameBeginCasePattern = 134,
							TokenNameRestrictedIdentifierWhen = 135,
							TokenNameUNDERSCORE = 34,
							TokenNameEOF = 40,
							TokenNameERROR = 142;
}
